name: CI

on: [push, pull_request]

jobs:
  reline:
    name: >-
      reline ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        ruby: [ 2.7, 2.6, 2.5 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: MSP-Greg/ruby-setup-ruby@add-path
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        shell: bash
        run:  bundle install
      - name: rake test
        shell: bash
        run:  bundle exec rake test
